.TH "iedit" "1" "1995-2002" "The XNC Package" "Edit by IVES" 
.PP 
.SH "NAME" 
es \- Edit files by IVES
.PP 
.SH "SYNOPSIS" 
\fBiedit\fP file
.PP 
.SH "DESCRIPTION" 
.PP 
This manual page describes the \fBiedit\fP program - simple interface to
\fBives\fP\&. The \fBiedit\fP can load files in \fBives\fP editor from command shell\&.
\fBIves\fP must be run before running \fBiedit\fP\&.
.PP 
.SH "FILES" 
.PP 
The \fBiedit\fP program requires no configuration files\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBxnc\fP, \fBives\fP, \fBiview\fP
.PP 
.SH "BUGS" 
.PP 
There may be bugs in the \fBiedit\fP, but that\'s not very likely\&.
But if you\'ll find the bug then please, send complete description to
the author\&.
.PP 
.SH "AUTHOR" 
.PP 
Leonid Khramov (leo@xnc\&.dubna\&.su) Russia, St\&.Petersburg 2002
