.TH "iview" "1" "1995-2002" "The XNC Package" "View files by IVES" 
.PP 
.SH "NAME" 
vs \- View files by IVES
.PP 
.SH "SYNOPSIS" 
\fBiview\fP file
.PP 
.SH "DESCRIPTION" 
.PP 
This manual page describes the \fBiview\fP program - simple interface to
\fBives\fP\&. The \fBiview\fP can load files in \fBives\fP viewer from 
command shell\&. \fBIves\fP must be run before running \fBiview\fP\&.
.PP 
.SH "FILES" 
.PP 
The \fBiview\fP program requires no configuration files\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBxnc\fP, \fBives\fP, \fBiedit\fP
.PP 
.SH "BUGS" 
.PP 
There may be bugs in the \fBiview\fP, but that\'s not very likely\&.
But if you\'ll find the bug then please, send complete description to
the author\&.
.PP 
.SH "AUTHOR" 
.PP 
Leonid Khramov (leo@xnc\&.dubna\&.su) Russia, St\&.Petersburg 2002
