.TH "xjpegroot" "1" "1995-1999" "The XNC Package" "XJpegRoot" 
.PP 
.SH "NAME" 
xjpegroot \- Image to background installer
.PP 
.SH "SYNOPSIS" 
\fBxjpegroot\fP [-d xdisplay] -c/-t imagefile
.PP 
.SH "DESCRIPTION" 
.PP 
This manual page describes the \fBxjpegroot\fP program, the image to
screen background installer for X Window\&.
\fBxjpegroot\fP can load and install images to background from various
formats, such as GIF, JPEG, PNG, PCX, BMP, XBM, XPM, TIFF,
TGA and PhotoCD\&.
Images may be intalled in tiling or in center mode\&.
.PP 
.SH "OPTIONS" 
.PP 
.IP 
.IP "-d xdisplay" 
Connect to X Server \fIxdisplay\fP\&.
.IP "-c" 
Install image in center of the screen, don\'t do tiling\&.
.IP "-t" 
Install image in tiling mode\&.
.PP 
.SH "FILES" 
.PP 
The \fBxjpegroot\fP program requires no configuration files\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBxnc\fP, \fBives\fP, \fBvs\fP, \fBes\fP
.PP 
.SH "BUGS" 
.PP 
There may be bugs in the \fBxjpegroot\fP, but that\'s not very likely\&.
But if you\'ll find the bug then please, send complete description to
the author\&.
.PP 
.SH "AUTHOR" 
.PP 
Leonid Khramov (leo@xnc\&.dubna\&.su)
